<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Authors>Niladri</Authors>
    <Company>Plugin.Maui.OfflineSync</Company>
    <Copyright>Copyright © Niladri</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
